### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by usorfaitheloho** [usorfaitheloho/Portfolio#8]

**Comment by victorokoroji** [comment]
Nice job so far. I think you should consider moving your nav items into the nav tag enclosed in the header tag . Having two different nav tags does not improve accessibility

**Comment by keza681** [comment]
Hi Faith,
Your project looks nice 👍  and I leaved a ⭐ on it.

**Comment by victorokoroji** [comment]
You can use css to hide the hamburger on desktop view and also hide the nav items on mobile view while keeping your hamburger and the nav items in the same nav tag
